apiVersion: apps/v1
kind: Deployment
metadata:
  name: argus-core
  namespace: argus
  labels:
    app: argus-core
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argus-core
  template:
    metadata:
      labels:
        app: argus-core
        component: api
    spec:
      containers:
      - name: argus-core
        image: argus/argus-core:1.0.0
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: argus-secrets
              key: anthropic-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/anomaly/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/anomaly/health
            port: http
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: argus-core-service
  namespace: argus
  labels:
    app: argus-core
spec:
  selector:
    app: argus-core
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argus-core-config
  namespace: argus
data:
  application-kubernetes.yml: |
    server:
      port: 8080
    spring:
      application:
        name: argus-core
      cache:
        type: simple
    anthropic:
      api:
        url: https://api.anthropic.com
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: always
    logging:
      level:
        com.argus: INFO
        root: INFO