server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: argus-ui-scheduler
  
  # Database Configuration (H2)
  datasource:
    url: jdbc:h2:mem:argusdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        
  # Thymeleaf Configuration
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    
  jackson:
    serialization:
      indent-output: true

# Argus Configuration
argus:
  core:
    url: http://localhost:8080
  scheduler:
    cron: "0 0 */4 * * *"  # Every 4 hours
    enabled: true

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# Application Information
info:
  app:
    name: Argus UI Scheduler
    description: Web Dashboard and Scheduler for Banner Anomaly Detection
    version: 1.0.0

# Logging Configuration
logging:
  level:
    com.argus: INFO
    org.springframework.web: INFO
    org.springframework.scheduling: INFO
    org.hibernate.SQL: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n"

# HTTP Client Configuration
spring.webflux:
  timeout:
    connect: 30s
    read: 60s
    write: 30s